/**
 * Dados de exemplo pra prévia da Biblioteca.
 *
 * Fictício de propósito. Usado como fallback quando `YOUTUBE_API_KEY` não
 * está configurada ou o radar real (`./radar.ts`) falha — ver page.tsx da
 * Biblioteca. Isso mantém a tela sempre funcional, mesmo sem a chave.
 */

import type { ItemBiblioteca } from "./tipos";

export type { ItemBiblioteca };

// Datas relativas a agora, pra não ficarem "publicado há 3 anos" com o tempo.
function diasAtras(n: number): string {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();
}

export const NICHOS_BIBLIOTECA = [
  "curiosidades",
  "mar e vida marinha",
  "natureza",
  "automotivo",
  "culinária",
  "fitness",
  "finanças pessoais",
] as const;

export const VIDEOS_EXEMPLO: ItemBiblioteca[] = [
  {
    id: "1",
    titulo: "5 fatos sobre o espaço que parecem mentira (mas não são)",
    canal: "Fatos Rápidos",
    nicho: "curiosidades",
    plataforma: "youtube",
    visualizacoes: 8_200_000,
    curtidas: 610_000,
    publicado_em: diasAtras(2),
    duracao_s: 42,
    tem_legenda_embutida: true,
    emoji: "🌌",
  },
  {
    id: "2",
    titulo: "Por que esse animal foi extinto e ninguém percebeu?",
    canal: "Curioso Demais",
    nicho: "curiosidades",
    plataforma: "tiktok",
    visualizacoes: 3_400_000,
    curtidas: 290_000,
    publicado_em: diasAtras(9),
    duracao_s: 31,
    tem_legenda_embutida: false,
    emoji: "🧠",
  },
  {
    id: "3",
    titulo: "O polvo que muda de cor em 1 segundo",
    canal: "Vida no Fundo do Mar",
    nicho: "mar e vida marinha",
    plataforma: "youtube",
    visualizacoes: 5_900_000,
    curtidas: 480_000,
    publicado_em: diasAtras(1),
    duracao_s: 38,
    tem_legenda_embutida: false,
    emoji: "🐙",
  },
  {
    id: "4",
    titulo: "Mergulhei sem tanque de oxigênio e achei isso",
    canal: "Oceano Vivo",
    nicho: "mar e vida marinha",
    plataforma: "instagram",
    visualizacoes: 2_100_000,
    curtidas: 175_000,
    publicado_em: diasAtras(14),
    duracao_s: 55,
    tem_legenda_embutida: true,
    emoji: "🐠",
  },
  {
    id: "5",
    titulo: "A trilha mais perigosa da América do Sul",
    canal: "Trilha Selvagem",
    nicho: "natureza",
    plataforma: "youtube",
    visualizacoes: 1_800_000,
    curtidas: 132_000,
    publicado_em: diasAtras(21),
    duracao_s: 47,
    tem_legenda_embutida: false,
    emoji: "🏔️",
  },
  {
    id: "6",
    titulo: "Timelapse de uma flor abrindo que viralizou do nada",
    canal: "Natureza em Detalhe",
    nicho: "natureza",
    plataforma: "tiktok",
    visualizacoes: 4_600_000,
    curtidas: 510_000,
    publicado_em: diasAtras(4),
    duracao_s: 18,
    tem_legenda_embutida: true,
    emoji: "🌸",
  },
  {
    id: "7",
    titulo: "Troquei o motor em 60 segundos (acelerado)",
    canal: "Garagem 500",
    nicho: "automotivo",
    plataforma: "youtube",
    visualizacoes: 2_900_000,
    curtidas: 205_000,
    publicado_em: diasAtras(18),
    duracao_s: 52,
    tem_legenda_embutida: false,
    emoji: "🔧",
  },
  {
    id: "8",
    titulo: "O carro mais barato que anda mais rápido que um esportivo",
    canal: "Rodas & Motor",
    nicho: "automotivo",
    plataforma: "tiktok",
    visualizacoes: 1_500_000,
    curtidas: 118_000,
    publicado_em: diasAtras(6),
    duracao_s: 29,
    tem_legenda_embutida: true,
    emoji: "🏎️",
  },
  {
    id: "9",
    titulo: "Fiz o mesmo prato com 3 ingredientes e ninguém acreditou",
    canal: "Sabor de Casa",
    nicho: "culinária",
    plataforma: "instagram",
    visualizacoes: 6_700_000,
    curtidas: 720_000,
    publicado_em: diasAtras(3),
    duracao_s: 34,
    tem_legenda_embutida: true,
    emoji: "🍳",
  },
  {
    id: "10",
    titulo: "O truque do restaurante que ninguém te conta",
    canal: "Cozinha Rápida",
    nicho: "culinária",
    plataforma: "youtube",
    visualizacoes: 3_200_000,
    curtidas: 240_000,
    publicado_em: diasAtras(11),
    duracao_s: 40,
    tem_legenda_embutida: false,
    emoji: "🍜",
  },
  {
    id: "11",
    titulo: "Treino de 5 minutos que substitui 1 hora de academia",
    canal: "Bora Treinar",
    nicho: "fitness",
    plataforma: "tiktok",
    visualizacoes: 9_100_000,
    curtidas: 980_000,
    publicado_em: diasAtras(5),
    duracao_s: 25,
    tem_legenda_embutida: true,
    emoji: "💪",
  },
  {
    id: "12",
    titulo: "O erro na dieta que trava seu emagrecimento",
    canal: "Corpo em Foco",
    nicho: "fitness",
    plataforma: "youtube",
    visualizacoes: 2_400_000,
    curtidas: 190_000,
    publicado_em: diasAtras(25),
    duracao_s: 44,
    tem_legenda_embutida: false,
    emoji: "🥗",
  },
  {
    id: "13",
    titulo: "Como eu saí das dívidas em 8 meses (com planilha)",
    canal: "Grana no Bolso",
    nicho: "finanças pessoais",
    plataforma: "youtube",
    visualizacoes: 1_900_000,
    curtidas: 140_000,
    publicado_em: diasAtras(28),
    duracao_s: 58,
    tem_legenda_embutida: true,
    emoji: "💸",
  },
  {
    id: "14",
    titulo: "Onde eu guardaria R$ 1.000 hoje (não é poupança)",
    canal: "Investe Fácil",
    nicho: "finanças pessoais",
    plataforma: "tiktok",
    visualizacoes: 2_700_000,
    curtidas: 225_000,
    publicado_em: diasAtras(8),
    duracao_s: 33,
    tem_legenda_embutida: false,
    emoji: "📈",
  },
];
