/**
 * Dados de exemplo pra prévia da aba Viral.
 *
 * Fictício de propósito. Usado como fallback quando `PEXELS_API_KEY` não
 * está configurada ou a busca real (`./pexels.ts`) falha — mesmo padrão da
 * Biblioteca (ver src/lib/biblioteca/videos-exemplo.ts).
 */

import type { ClipeViral } from "./tipos";

export const CLIPES_EXEMPLO: ClipeViral[] = [
  {
    id: "1",
    descricao: "Fumaça colorida se espalhando devagar no escuro",
    nicho: "curiosidades",
    duracao_s: 12,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "💨",
  },
  {
    id: "2",
    descricao: "Close de estrelas girando no céu noturno (timelapse)",
    nicho: "curiosidades",
    duracao_s: 15,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "✨",
  },
  {
    id: "3",
    descricao: "Onda quebrando em câmera lenta, vista de cima",
    nicho: "mar e vida marinha",
    duracao_s: 10,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🌊",
  },
  {
    id: "4",
    descricao: "Cardume de peixes coloridos nadando perto de um recife",
    nicho: "mar e vida marinha",
    duracao_s: 14,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🐟",
  },
  {
    id: "5",
    descricao: "Luz do sol passando entre folhas de uma floresta",
    nicho: "natureza",
    duracao_s: 11,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🌳",
  },
  {
    id: "6",
    descricao: "Cachoeira caindo entre pedras, plano fixo",
    nicho: "natureza",
    duracao_s: 13,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "💧",
  },
  {
    id: "7",
    descricao: "Roda de carro girando em alta velocidade, close",
    nicho: "automotivo",
    duracao_s: 8,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🛞",
  },
  {
    id: "8",
    descricao: "Painel de carro esportivo ligando à noite, luzes acendendo",
    nicho: "automotivo",
    duracao_s: 9,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🏎️",
  },
  {
    id: "9",
    descricao: "Calda de chocolate escorrendo sobre um bolo, câmera lenta",
    nicho: "culinária",
    duracao_s: 10,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🍫",
  },
  {
    id: "10",
    descricao: "Vapor subindo de um prato recém-feito, luz quente",
    nicho: "culinária",
    duracao_s: 9,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🍲",
  },
  {
    id: "11",
    descricao: "Gotas de suor caindo durante um treino, câmera lenta",
    nicho: "fitness",
    duracao_s: 8,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "💦",
  },
  {
    id: "12",
    descricao: "Barras de peso sendo empilhadas numa academia",
    nicho: "fitness",
    duracao_s: 10,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "🏋️",
  },
  {
    id: "13",
    descricao: "Notas de dinheiro sendo contadas à mão, close",
    nicho: "finanças pessoais",
    duracao_s: 7,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "💵",
  },
  {
    id: "14",
    descricao: "Gráfico de crescimento sendo desenhado numa tela",
    nicho: "finanças pessoais",
    duracao_s: 9,
    largura: 1080,
    altura: 1920,
    autor: "Banco de exemplo",
    emoji: "📊",
  },
];
